# Generated by Django 4.2.11 on 2024-04-23 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('condition', models.CharField(max_length=3)),
                ('image', models.ImageField(blank=True, null=True, upload_to='house_images/')),
            ],
        ),
    ]
