# Generated by Django 4.2.11 on 2024-04-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addis_house', '0002_alter_house_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
